We start with concatanating two datasets obtained from two reviews and reorder them so that we can manually check if same entries in those papers do not match:

In [8]:
import pandas as pd
from rdkit import Chem

# load data
df1 = pd.read_csv('../data/Gd/reviews/dioury2014.csv')
df2 = pd.read_csv('../data/Gd/reviews/uzal2022.csv')

# filter columns
cols = ['ID', 'smiles', 'doi', 'lgK']
df1 = df1.loc[:,cols]
df2 = df2.loc[:,cols]

# add source info
df1.insert(3, 'source', 'dioury2014')
df2.insert(3, 'source', 'uzal2022')

# merge
df = pd.concat([df1, df2], ignore_index = True).rename(columns = {'ID': 'sourceID'})

# add compound IDs
IDs = {smi: f'rev_{i+1:03d}' for i, smi in enumerate(df.smiles.drop_duplicates())}
df.insert(0, 'ID', [IDs[smi] for smi in df.smiles])

# sort
df = df.sort_values(by = ['ID', 'doi', 'source', 'lgK'])

# view table
pd.set_option('display.max_rows', 400)
df.loc[:,['ID','doi','source','sourceID','lgK']]

,ID,doi,source,sourceID,lgK
0,rev_001,10.1002/ejoc.200400264,dioury2014,1,9.34
361,rev_001,10.1002/ejoc.200400264,uzal2022,B43,9.34
1,rev_001,10.1021/ic960794b,dioury2014,1,12.50
2,rev_002,10.1021/ic960794b,dioury2014,2,19.30
352,rev_003,10.1002/chem.201705528,uzal2022,B34,18.28
3,rev_003,10.1021/ic0608750,dioury2014,3,20.39
351,rev_003,10.1021/ic0608750,uzal2022,B34,20.39
4,rev_003,10.1021/ic960794b,dioury2014,3,21.00
5,rev_004,10.1021/bc8004914,dioury2014,4,19.42
353,rev_004,10.1021/bc8004914,uzal2022,B35,19.42
6,rev_005,10.1021/ic00112a040,dioury2014,5,14.50
359,rev_005,10.1021/ic00112a040,uzal2022,B41,14.50
7,rev_006,10.1021/ic00112a040,dioury2014,6,16.60
354,rev_006,10.1021/ic00112a040,uzal2022,B36,16.60
9,rev_007,10.1021/ic00046a015,dioury2014,7,17.44
8,rev_007,10.1021/ic00091a032,dioury2014,7,17.40
10,rev_008,10.1021/ic00046a015,dioury2014,8,12.34
11,rev_009,10.1021/ic00046a015,dioury2014,9,15.94
13,rev_010,10.1016/0730-725x(92)90444-5,dioury2014,10,18.07
12,rev_010,10.1021/ic00067a022,dioury2014,10,18.02
375,rev_010,10.1021/ic00067a022,uzal2022,D5,18.02
14,rev_011,10.1002/chin.198201094,dioury2014,11,16.27
15,rev_012,10.1021/ic00168a010,dioury2014,12,11.93
371,rev_012,10.1021/ic00168a010,uzal2022,D1,11.93
16,rev_013,10.1021/ic00046a015,dioury2014,13,15.39
17,rev_014,10.1021/ic00046a015,dioury2014,14,15.56
18,rev_015,10.1021/ic00046a015,dioury2014,15,14.49
19,rev_016,10.1021/ic00046a015,dioury2014,16,15.14
20,rev_016,10.1021/ic00091a032,dioury2014,16,15.30
22,rev_017,10.1016/s0020-1693(97)05660-0,dioury2014,17,17.30
21,rev_017,10.1021/ic00067a022,dioury2014,17,17.23
379,rev_017,10.1021/ic00067a022,uzal2022,E3,17.23
23,rev_018,10.1006/mchj.1996.0026,dioury2014,18,11.49
24,rev_019,10.1021/ic00223a025,dioury2014,19,11.66
377,rev_019,10.1021/ic00223a025,uzal2022,E1,11.66
363,rev_020,10.1016/S0020-1693(00)80229-7,uzal2022,B45,13.77
25,rev_020,10.1016/s0020-1693(00)80229-7,dioury2014,20,13.77
26,rev_020,10.1021/ic00006a021,dioury2014,20,14.73
362,rev_021,10.1016/S0020-1693(00)80229-7,uzal2022,B44,19.17
27,rev_021,10.1016/s0020-1693(00)80229-7,dioury2014,21,19.17
35,rev_022,10.1002/mrm.1910220215,dioury2014,22,25.60
29,rev_022,10.1016/0020-1693(94)03964-x,dioury2014,22,23.60
32,rev_022,10.1016/0020-1693(96)05182-1,dioury2014,22,24.67
30,rev_022,10.1016/s0020-1693(00)80229-7,dioury2014,22,24.00
28,rev_022,10.1021/ic00032a034,dioury2014,22,22.10
37,rev_022,10.1021/ic00032a035,dioury2014,22,27.00
34,rev_022,10.1021/ic00094a021,dioury2014,22,25.30
31,rev_022,10.1021/ic00253a038,dioury2014,22,24.60
317,rev_022,10.1021/ic00253a038,uzal2022,B1,24.70
36,rev_022,10.1039/a700519i,dioury2014,22,26.03
33,rev_022,10.1351/pac200577081445,dioury2014,22,25.00
38,rev_022,10.3406/barb.1978.58463,dioury2014,22,27.00
39,rev_022,10.3406/barb.1978.58463,dioury2014,22,28.00
40,rev_023,10.1002/mrm.1910220215,dioury2014,23,26.30
319,rev_023,10.1002/mrm.1910220215,uzal2022,B3,26.30
41,rev_024,10.1021/ic0353007,dioury2014,24,24.20
42,rev_025,10.1021/ic00032a035,dioury2014,25,25.93
335,rev_025,10.1021/ic00032a035,uzal2022,B18,25.93
43,rev_026,10.1021/ic00032a035,dioury2014,26,25.95
44,rev_027,10.1016/s0010-8545(99)00237-4,dioury2014,27,23.60
318,rev_027,10.1021/ic2012827,uzal2022,B2,23.60
45,rev_028,10.1021/ic2012843,dioury2014,28,21.53
46,rev_029,10.1021/ic2012843,dioury2014,29,23.86
47,rev_030,10.1002/ejic.200300085,dioury2014,30,24.03
48,rev_031,10.1021/ic00302a049,dioury2014,31,20.10
334,rev_031,10.1021/ic00302a049,uzal2022,B17,20.10
49,rev_032,10.1021/ci500346w,dioury2014,32,21.54
50,rev_033,10.1021/ic00095a028,dioury2014,33,22.30
336,rev_033,10.1021/ic00095a028,uzal2022,B19,22.30
51,rev_034,10.1021/ic00094a021,dioury2014,34,23.80
337,rev_034,10.1021/ic00095a028,uzal2022,B20,23.80
52,rev_034,10.1039/a909098c,dioury2014,34,24.50
53,rev_035,10.1021/ic00095a028,dioury2014,35,23.90
338,rev_035,10.1021/ic00095a028,uzal2022,B21,23.90
54,rev_036,10.1016/0020-1693(96)05094-3,dioury2014,36,18.70
55,rev_036,10.1016/0020-1693(96)05094-3,dioury2014,36,20.80
56,rev_036,10.1016/0020-1693(96)05094-3,dioury2014,36,21.80
57,rev_037,10.1039/a909098c,dioury2014,37,19.40
58,rev_038,10.1016/s0010-8545(99)00237-4,dioury2014,38,18.37
59,rev_039,10.1021/ic00067a022,dioury2014,39,21.60
365,rev_039,10.1021/ic00067a022,uzal2022,B47,21.60
62,rev_040,10.1016/0020-1693(96)05094-3,dioury2014,40,22.02
331,rev_040,10.1021/acs.inorgchem.8b00473,uzal2022,B14,19.06
60,rev_040,10.1021/ic00094a021,dioury2014,40,21.00
330,rev_040,10.1021/ic4025958,uzal2022,B14,21.56
61,rev_040,10.1351/pac200577081445,dioury2014,40,22.02
63,rev_041,10.1039/a909098c,dioury2014,41,18.82
349,rev_041,10.1039/a909098c,uzal2022,B32,18.82
64,rev_042,10.1016/s0010-8545(99)00237-4,dioury2014,42,18.21
65,rev_043,10.1021/ic961131x,dioury2014,43,21.10
343,rev_043,10.1021/ic961131x,uzal2022,B26,21.10
66,rev_044,10.1021/ic961131x,dioury2014,44,22.50
344,rev_044,10.1021/ic961131x,uzal2022,B27,22.50
68,rev_045,10.1002/ejic.200700354,dioury2014,45,13.12
321,rev_045,10.1002/ejic.200700354,uzal2022,B5,13.12
67,rev_045,10.1021/ja00130a008,dioury2014,45,10.05
70,rev_046,10.1002/ejic.200700354,dioury2014,46,13.54
322,rev_046,10.1002/ejic.200700354,uzal2022,B6,13.54
69,rev_046,10.1039/a909098c,dioury2014,46,12.80
71,rev_047,10.1002/ejic.200700354,dioury2014,47,14.83
324,rev_047,10.1002/ejic.200700354,uzal2022,B8,14.83
323,rev_048,10.1002/ejic.200700354,uzal2022,B7,14.54
72,rev_048,10.1002/hlca.200590042,dioury2014,48,14.54
73,rev_049,10.1021/ic00009a027,dioury2014,49,15.10
74,rev_050,10.1021/ic00009a027,dioury2014,50,14.70
75,rev_051,10.1021/ic00009a027,dioury2014,51,10.40
76,rev_052,10.1021/ic00009a027,dioury2014,52,13.70
366,rev_052,10.1021/ic00009a027,uzal2022,C1,13.70
77,rev_052,10.1021/ic00253a038,dioury2014,52,14.30
78,rev_053,10.1524/ract.1993.61.34.207,dioury2014,53,12.80
79,rev_054,10.1002/ejic.201101162,dioury2014,54,13.90
367,rev_054,10.1002/ejic.201101162,uzal2022,C2,13.90
80,rev_055,10.1002/chem.200501390,dioury2014,55,15.80
368,rev_055,10.1002/chem.200501390,uzal2022,C3,15.80
81,rev_056,10.1039/b907738c,dioury2014,56,15.10
369,rev_056,10.1039/b907738c,uzal2022,C4,15.10
83,rev_057,10.1016/0022-1902(81)80122-4,dioury2014,57,20.42
82,rev_057,10.1016/s0010-8545(00)80110-1,dioury2014,57,20.41
242,rev_058,10.1016/S0010-8545(99)00237-4,uzal2022,A2,21.66
84,rev_058,10.1016/s0010-8545(99)00237-4,dioury2014,58,21.66
85,rev_059,10.1515/znc-1997-7-814,dioury2014,59,19.00
87,rev_060,10.1002/ejic.200901261,dioury2014,60,22.03
239,rev_060,10.1002/ejic.200901261,uzal2022,A1,22.03
89,rev_060,10.1002/mrm.1910080208,dioury2014,60,22.26
240,rev_060,10.1002/mrm.1910080208,uzal2022,A1,22.26
94,rev_060,10.1002/mrm.1910220215,dioury2014,60,22.90
95,rev_060,10.1016/0022-1902(59)80246-3,dioury2014,60,23.01
92,rev_060,10.1016/0022-1902(62)80236-x,dioury2014,60,22.46
241,rev_060,10.1016/0022-1902(62)80236-x,uzal2022,A1,22.46
86,rev_060,10.1016/0022-1902(77)80538-1,dioury2014,60,20.73
88,rev_060,10.1021/ic00094a021,dioury2014,60,22.20
90,rev_060,10.1021/ic00253a038,dioury2014,60,22.30
93,rev_060,10.1021/ic981072i,dioury2014,60,22.52
91,rev_060,10.1021/ic991189m,dioury2014,60,22.46
96,rev_061,10.1002/ejic.200901261,dioury2014,61,21.91
268,rev_061,10.1002/ejic.200901261,uzal2022,A27,21.91
97,rev_061,10.1016/s0010-8545(99)00237-4,dioury2014,61,22.58
98,rev_061,10.1021/ic00107a017,dioury2014,61,22.59
99,rev_062,10.1021/jm9602118,dioury2014,62,21.99
244,rev_062,10.1021/jm9602118,uzal2022,A4,22.00
100,rev_063,10.1016/s0010-8545(99)00237-4,dioury2014,63,22.76
101,rev_063,10.1021/ic981072i,dioury2014,63,23.46
102,rev_064,10.1002/chem.200204612,dioury2014,64,19.20
104,rev_065,10.1021/ic991189m,dioury2014,65b,20.42
103,rev_065,10.1021/ic991189m,dioury2014,65a,20.71
269,rev_066,10.1016/S0277-5387(00)86256-7,uzal2022,A28,19.74
105,rev_066,10.1016/s0277-5387(00)86256-7,dioury2014,66,19.74
106,rev_067,10.1002/chem.200204612,dioury2014,67,13.00
276,rev_067,10.1002/chem.200204612,uzal2022,A34,17.50
250,rev_068,10.1016/S0277-5387(00)00502-7,uzal2022,A10,21.59
107,rev_068,10.1016/s0277-5387(00)00502-7,dioury2014,68,21.59
108,rev_069,10.1016/s0277-5387(00)00502-7,dioury2014,69,18.48
109,rev_070,10.1039/b005298l,dioury2014,70,19.90
249,rev_070,10.1039/b005298l,uzal2022,A9,19.90
110,rev_071,10.1039/b005298l,dioury2014,71,19.30
270,rev_071,10.1039/b005298l,uzal2022,A29,19.40
111,rev_072,10.1002/mrm.1910080208,dioury2014,72,19.68
266,rev_072,10.1002/mrm.1910080208,uzal2022,A25,19.68
112,rev_073,10.1002/mrm.1910080208,dioury2014,73,18.91
267,rev_073,10.1002/mrm.1910080208,uzal2022,A26,18.91
113,rev_074,10.1021/ic00212a005,dioury2014,74,17.79
246,rev_074,10.1021/ic00212a005,uzal2022,A6,17.79
114,rev_075,10.1021/ic00212a005,dioury2014,75,15.42
115,rev_076,10.1039/b107456n,dioury2014,76,17.33
116,rev_077,10.1039/b107456n,dioury2014,77,17.16
117,rev_078,10.1039/b107456n,dioury2014,78,17.44
118,rev_079,10.1002/mrm.1910080208,dioury2014,79,16.30
252,rev_079,10.1002/mrm.1910080208,uzal2022,A12,16.30
254,rev_080,10.1039/B514173G,uzal2022,A14,14.60
119,rev_080,10.1039/b514173g,dioury2014,80,14.60
256,rev_081,10.1002/chem.201405967,uzal2022,A16,16.72
120,rev_081,10.1002/ejic.200901261,dioury2014,81,16.64
257,rev_081,10.1016/0730-725X(90)90055-7,uzal2022,A16,16.85
121,rev_081,10.1016/0730-725x(90)90055-7,dioury2014,81,16.85
122,rev_082,10.1002/mrm.1910080208,dioury2014,82,16.23
258,rev_082,10.1002/mrm.1910080208,uzal2022,A17,16.23
123,rev_083,10.1039/a605483h,dioury2014,83,17.07
259,rev_084,10.1039/B514173G,uzal2022,A18,16.50
125,rev_084,10.1039/b514173g,dioury2014,84,16.50
124,rev_084,10.1097/00004424-199009001-00026,dioury2014,84,15.90
126,rev_085,10.1039/a605483h,dioury2014,85,17.15
127,rev_086,10.1039/a605483h,dioury2014,86,16.48
128,rev_087,10.1016/s0277-5387(97)00476-2,dioury2014,87,16.85
130,rev_088,10.1016/s0020-1693(96)05522-3,dioury2014,88,16.84
129,rev_088,10.1097/00004424-199009001-00026,dioury2014,88,16.48
131,rev_088,10.1097/00004424-199111001-00074,dioury2014,88,16.84
255,rev_088,10.1097/00004424-199111001-00077,uzal2022,A15,16.84
132,rev_089,10.1016/s0277-5387(97)00476-2,dioury2014,89,16.82
133,rev_090,10.1016/s0277-5387(97)00476-2,dioury2014,90,16.91
134,rev_091,10.1097/00004424-199111001-00074,dioury2014,91,16.70
264,rev_092,10.1039/B514173G,uzal2022,A23,19.00
135,rev_092,10.1039/b514173g,dioury2014,92,19.00
137,rev_093,10.1016/s0020-1693(96)05522-3,dioury2014,93,17.69
136,rev_093,10.1097/00004424-199111001-00077,dioury2014,93,17.68
262,rev_093,10.1097/00004424-199111001-00077,uzal2022,A21,17.68
138,rev_094,10.1097/00004424-199111001-00074,dioury2014,94,17.10
139,rev_095,10.1097/00004424-199111001-00074,dioury2014,95,19.20
140,rev_096,10.1016/s0020-1693(96)05522-3,dioury2014,96,17.49
141,rev_096,10.1097/00004424-199111001-00074,dioury2014,96,17.49
263,rev_096,10.1097/00004424-199111001-00077,uzal2022,A22,17.49
265,rev_097,10.1016/0730-725X(90)90055-7,uzal2022,A24,16.83
142,rev_097,10.1016/0730-725x(90)90055-7,dioury2014,97,16.83
143,rev_098,10.1016/0730-725x(92)90444-5,dioury2014,98,23.65
144,rev_099,10.1021/ic00110a019,dioury2014,99,13.12
253,rev_099,10.1021/ic00110a019,uzal2022,A13,13.12
145,rev_100,10.1039/b417272h,dioury2014,100,17.93
150,rev_101,10.1002/chin.198535056,dioury2014,101,17.40
149,rev_101,10.1002/hlca.19540370402,dioury2014,101,17.37
146,rev_101,10.1016/0022-1902(77)80538-1,dioury2014,101,16.28
287,rev_101,10.1016/0048-9697(87)90127-6,uzal2022,A43,17.35
148,rev_101,10.1016/s0010-8545(99)00237-4,dioury2014,101,17.35
152,rev_101,10.1021/ic00094a021,dioury2014,101,17.70
147,rev_101,10.1021/ja01113a020,dioury2014,101,16.70
151,rev_101,10.1135/cccc19781450,dioury2014,101,17.53
154,rev_102,10.1016/0022-1902(64)80019-1,dioury2014,102,18.21
155,rev_102,10.1016/s0003-2670(01)95804-0,dioury2014,102,18.87
153,rev_102,10.1135/cccc19781450,dioury2014,102,18.15
156,rev_103,10.1135/cccc19781450,dioury2014,103,17.09
157,rev_104,10.1016/s0003-2670(01)95804-0,dioury2014,104,18.24
162,rev_105,10.1002/chin.198535056,dioury2014,105,19.50
159,rev_105,10.1002/hlca.19540370402,dioury2014,105,18.77
160,rev_105,10.1016/0022-1902(62)80018-9,dioury2014,105,18.80
158,rev_105,10.1016/0022-1902(77)80538-1,dioury2014,105,18.12
161,rev_105,10.1016/s0003-2670(00)84867-9,dioury2014,105,18.97
163,rev_106,10.1002/hlca.19640470715,dioury2014,106,13.74
302,rev_106,10.1021/ic00224a041,uzal2022,A58,13.76
164,rev_107,10.1002/ejic.201101294,dioury2014,107,12.30
165,rev_108,10.1021/ic00224a041,dioury2014,108,13.94
303,rev_108,10.1021/ic00224a041,uzal2022,A59,13.94
166,rev_109,10.1016/s0277-5387(00)87165-x,dioury2014,109,10.37
167,rev_110,10.1021/ic00178a027,dioury2014,110,11.74
281,rev_110,10.1021/ic00178a027,uzal2022,A38,11.74
283,rev_111,10.1021/ic5020225,uzal2022,A40,17.66
168,rev_111,10.1021/j100808a028,dioury2014,111,16.94
169,rev_111,10.1021/j100808a028,dioury2014,111,17.50
284,rev_111,10.1021/j100808a028,uzal2022,A40,17.50
171,rev_112,10.1002/jccs.199000033,dioury2014,112,10.94
285,rev_112,10.1246/BCSJ.66.3377,uzal2022,A41,10.60
170,rev_112,10.1246/bcsj.66.3377,dioury2014,112,10.60
172,rev_113,10.1021/ic00213a019,dioury2014,113,15.21
280,rev_113,10.1021/ic00213a019,uzal2022,A37,15.21
294,rev_114,10.1021/ic502966m,uzal2022,A50,20.23
173,rev_114,10.1039/b416150e,dioury2014,114,15.10
295,rev_115,10.1016/S0021-9673(01)91745-5,uzal2022,A51,12.98
174,rev_115,10.1021/ic00234a009,dioury2014,115,12.98
176,rev_116,10.1016/s0010-8545(99)00237-4,dioury2014,116,12.58
175,rev_116,10.1021/ic50181a065,dioury2014,116,12.40
297,rev_117,10.1016/0020-1693(94)04398-F,uzal2022,A53,17.54
177,rev_117,10.1016/0020-1693(94)04398-f,dioury2014,117,17.54
178,rev_118,10.1515/znc-1997-7-814,dioury2014,118,15.56
298,rev_118,10.1515/znc-1997-7-814,uzal2022,A54,15.56
179,rev_119,10.1016/0022-1902(77)80538-1,dioury2014,119,14.80
299,rev_119,10.1016/00221902(61)80275-3,uzal2022,A55,15.22
180,rev_119,10.1021/ja01582a007,dioury2014,119,15.10
181,rev_119,10.1021/ja01582a007,dioury2014,119,15.40
182,rev_120,10.1016/s0020-1693(00)84982-8,dioury2014,120,21.18
183,rev_121,10.1021/ic9613016,dioury2014,121,12.37
291,rev_121,10.1021/ic9613016,uzal2022,A47,12.37
184,rev_122,10.1021/ic00006a021,dioury2014,122,22.95
185,rev_123,10.1021/ic00006a021,dioury2014,123,15.88
186,rev_124,10.1021/ic00046a015,dioury2014,124,11.15
187,rev_124,10.1021/ic00091a032,dioury2014,124,11.40
188,rev_125,10.5012/jkcs.2004.48.6.577,dioury2014,125,9.98
189,rev_126,10.5012/jkcs.2004.48.6.577,dioury2014,126,16.57
190,rev_127,10.1006/mchj.1996.0026,dioury2014,127,11.23
380,rev_127,10.1006/mchj.1996.0026,uzal2022,E4,11.23
191,rev_128,10.1016/j.tet.2006.10.024,dioury2014,128,NaN
192,rev_129,10.1016/j.tet.2009.06.117,dioury2014,129,NaN
193,rev_130,10.1007/bf02594595,dioury2014,130,NaN
194,rev_131,10.1021/ja101518v,dioury2014,131,NaN
196,rev_132,10.1002/hlca.200590044,dioury2014,132,NaN
195,rev_132,10.1021/ja101518v,dioury2014,132,NaN
197,rev_133,10.1002/hlca.200590044,dioury2014,133,NaN
198,rev_134,10.1002/hlca.200590044,dioury2014,134,27.20
199,rev_135,10.1016/j.tetlet.2012.11.151,dioury2014,135,NaN
200,rev_136,10.1021/ic00038a023,dioury2014,136,26.40
201,rev_137,10.1021/ic00038a023,dioury2014,137,25.90
202,rev_138,10.1021/ic00065a019,dioury2014,138,25.30
204,rev_139,10.1021/ic961131x,dioury2014,139,19.10
205,rev_139,10.1021/ic961131x,dioury2014,139,19.40
341,rev_139,10.1021/ic961131x,uzal2022,B24,19.10
203,rev_139,10.1039/a803565b,dioury2014,139,13.06
206,rev_140,10.1021/ic202436j,dioury2014,140,NaN
345,rev_140,10.1039/C4DT02985B,uzal2022,B28,17.27
207,rev_141,10.1021/ic202436j,dioury2014,141,NaN
346,rev_141,10.1039/C4DT02985B,uzal2022,B29,17.59
208,rev_142,10.1016/0022-1902(81)80122-4,dioury2014,142,19.51
209,rev_142,10.1016/0223-5234(88)90094-3,dioury2014,142,28.40
286,rev_142,10.1016/0223-5234(88)90094-3,uzal2022,A42,28.40
210,rev_143,10.1021/jm980152t,dioury2014,143,NaN
211,rev_144,10.1021/jm980152t,dioury2014,144,NaN
212,rev_145,10.1021/ic951326p,dioury2014,145,NaN
213,rev_146,10.1007/bf00759053,dioury2014,146,16.71
214,rev_146,10.1007/bf00759053,dioury2014,146,18.40
215,rev_147,10.1002/chem.200204612,dioury2014,147,17.50
216,rev_147,10.1002/chem.200204612,dioury2014,147,18.75
275,rev_147,10.1002/chem.200204612,uzal2022,A33,13.00
217,rev_147,10.1039/a805837g,dioury2014,147,22.77
218,rev_148,10.1002/1522-2675(200204)85:4<1033::aid-hlca10...,dioury2014,148,23.79
219,rev_149,10.1039/b107456n,dioury2014,149,23.48
220,rev_150,10.1097/00004424-199009001-00026,dioury2014,150,15.34
221,rev_151,10.1097/00004424-199009001-00026,dioury2014,151,15.62
223,rev_152,10.1097/00004424-199009001-00026,dioury2014,152,20.82
222,rev_152,10.1097/00004424-199111001-00074,dioury2014,152,16.10
224,rev_153,10.1002/mrm.1910080208,dioury2014,153,15.32
225,rev_154,10.1097/00004424-199111001-00074,dioury2014,154,20.30
230,rev_155,10.1016/0022-1902(71)80023-4,dioury2014,155b,17.03
226,rev_155,10.1016/0022-1902(71)80023-4,dioury2014,155a,18.64
229,rev_155,10.1016/0022-1902(71)80024-6,dioury2014,155b,16.51
227,rev_155,10.1016/s0003-2670(01)95804-0,dioury2014,155a,18.78
228,rev_155,10.1021/ac60243a032,dioury2014,155a,18.84
233,rev_156,10.1016/0022-1902(81)80122-4,dioury2014,156,15.35
231,rev_156,10.1016/s0020-1693(00)80040-7,dioury2014,156,11.83
232,rev_156,10.1016/s0020-1693(00)80040-7,dioury2014,156,13.21
236,rev_157,10.1007/978-1-4613-4452-0,dioury2014,157,18.30
278,rev_157,10.1021/ic5020225,uzal2022,A36,19.37
234,rev_157,10.1021/j100808a028,dioury2014,157,18.13
235,rev_157,10.1021/j100808a028,dioury2014,157,18.21
279,rev_157,10.1021/j100808a028,uzal2022,A36,18.21
237,rev_158,10.1016/0020-1693(94)04012-5,dioury2014,158,18.89
293,rev_158,10.1016/0020-1693(94)04012-5,uzal2022,A49,18.89
238,rev_158,10.1515/ci.2000.22.1.24a,dioury2014,158,19.16
243,rev_159,10.1016/S0010-8545(99)00237-4,uzal2022,A3,22.23
245,rev_160,10.1021/ic800512k,uzal2022,A5,18.60
247,rev_161,10.1002/cmmi.131,uzal2022,A7,22.79
248,rev_162,10.1002/cmmi.131,uzal2022,A8,22.34
251,rev_163,10.1016/S0010-8545(99)00237-4,uzal2022,A11,21.72
260,rev_164,10.1021/acs.inorgchem.6b02158,uzal2022,A19,16.70
261,rev_165,10.1021/acs.inorgchem.6b02158,uzal2022,A20,16.17
271,rev_166,10.1016/S0010-8545(99)00237-4,uzal2022,A30,22.18
272,rev_167,10.1021/ic001117r,uzal2022,A31,22.06
273,rev_167,10.1021/ic001117r,uzal2022,A31,23.20
274,rev_168,10.1021/ic981072i,uzal2022,A32,23.46
277,rev_169,10.1039/b506702b,uzal2022,A35,13.44
282,rev_170,10.1039/b817343e,uzal2022,A39,18.60
288,rev_171,10.1016/S0277-5387(98)00273-3,uzal2022,A44,12.79
289,rev_172,10.1016/S0277-5387(98)00273-3,uzal2022,A45,12.76
290,rev_173,10.1039/b211060a,uzal2022,A46,10.30
292,rev_174,10.1016/0048-9697(87)90127-6,uzal2022,A48,8.10
296,rev_175,10.1021/ic50181a065,uzal2022,A52,12.40
300,rev_176,10.1016/0048-9697(87)90127-6,uzal2022,A56,19.60
301,rev_177,10.1002/chem.201503836,uzal2022,A57,20.68
304,rev_178,10.1246/bcsj.65.1566,uzal2022,A60,13.89
305,rev_179,10.1016/S0010-8545(99)00237-4,uzal2022,A61,7.88
306,rev_180,10.1021/ic50001a010,uzal2022,A62,11.54
307,rev_181,10.1021/ic50003a009,uzal2022,A63,6.68
309,rev_182,10.1016/S0010-8545(99)00237-4,uzal2022,A64,6.68
308,rev_182,10.1016/S0010-8545(99)00237-4,uzal2022,A64,6.80
310,rev_183,10.1021/ic50007a042,uzal2022,A65,9.01
311,rev_184,10.1016/S0010-8545(99)00237-4,uzal2022,A66,7.04
312,rev_185,10.1246/bcsj.62.2296,uzal2022,A67,13.55
313,rev_186,10.1016/S0020-1693(00)81210-4,uzal2022,A68,3.72
314,rev_187,10.1016/S0020-1693(00)81210-4,uzal2022,A69,14.73
315,rev_188,10.1016/S0020-1693(00)81210-4,uzal2022,A70,17.41
316,rev_189,10.1016/S0020-1693(00)81210-4,uzal2022,A71,18.00
320,rev_190,10.1021/ic0353007,uzal2022,B4,24.20
325,rev_191,10.1021/ic9600590,uzal2022,B9,28.80
326,rev_192,10.1021/ic00026a030,uzal2022,B10,16.50
327,rev_193,10.1002/ejic.200800859,uzal2022,B11,16.09
328,rev_194,10.1002/ejic.200800859,uzal2022,B12,14.40
329,rev_195,10.1002/1099-0682(200103)2001:3<813::aid-ejic8...,uzal2022,B13,12.19
332,rev_196,10.1021/ic2001915,uzal2022,B15,23.31
333,rev_197,10.1039/C4DT03939D,uzal2022,B16,22.25
339,rev_198,10.1135/cccc20051909,uzal2022,B22,27.50
340,rev_199,10.1021/acs.inorgchem.9b00267,uzal2022,B23,23.77

As a result of manual check we conclude that we can just drop repeating (SMILES, DOI) entries ignoring their source (one of two reviews):

In [ ]:
pd.set_option('display.max_rows', 20)

# drop unwanted data
df = df.drop_duplicates(['ID', 'doi']).reset_index(drop = True)
df

,ID,sourceID,smiles,doi,source,lgK
0,rev_001,1,O=C(O)CN1CCCN(CC(=O)O)Cc2cccc(n2)CN(CC(=O)O)CCC1,10.1002/ejoc.200400264,dioury2014,9.34
1,rev_001,1,O=C(O)CN1CCCN(CC(=O)O)Cc2cccc(n2)CN(CC(=O)O)CCC1,10.1021/ic960794b,dioury2014,12.50
2,rev_002,2,O=C(O)CN1CCCN(CC(=O)O)Cc2cccc(n2)CN(CC(=O)O)CC1,10.1021/ic960794b,dioury2014,19.30
352,rev_003,B34,O=C(O)CN1CCN(CC(=O)O)Cc2cccc(n2)CN(CC(=O)O)CC1,10.1002/chem.201705528,uzal2022,18.28
3,rev_003,3,O=C(O)CN1CCN(CC(=O)O)Cc2cccc(n2)CN(CC(=O)O)CC1,10.1021/ic0608750,dioury2014,20.39
...,...,...,...,...,...,...
388,rev_223,T8,O=C(O)CN(CCOCCN(CC(=O)O)Cc1cccc(C(=O)O)n1)Cc1c...,10.1021/acs.inorgchem.0c00372,uzal2022,20.50
389,rev_224,T9,O=P(O)(O)CN1CCNCCNCCN(CP(=O)(O)O)CC1,10.3390/molecules24183324,uzal2022,19.15
390,rev_225,T10,O=C(O)CN1CCN(CC(=O)O)CCN(C[C@@H](O)C(=O)O)CCN(...,10.1021/acs.inorgchem.1c01927,uzal2022,19.26
391,rev_226,T11,O=C(O)CN1Cc2cccc(n2)CN(CC(=O)O)Cc2cccc(n2)CN(C...,10.1021/acs.inorgchem.9b03345,uzal2022,18.30
392,rev_227,T12,CCCCNC(=O)CN(CCN(CCN(CC(=O)O)CC(=O)O)CC(=O)O)C...,10.1039/C7DT04104G,uzal2022,18.78

In [11]:
df = df.dropna()

df_shuffled = df.sample(frac=1, random_state=42)
df_unique_random = df_shuffled.drop_duplicates(subset=['smiles']).reset_index(drop=True) 
df_unique_random

,ID,sourceID,smiles,doi,source,lgK
0,rev_081,81,CNC(=O)CN(CCN(CCN(CC(=O)O)CC(=O)NC)CC(=O)O)CC(...,10.1016/0730-725x(90)90055-7,dioury2014,16.85
1,rev_022,22,O=C(O)CN1CCN(CC(=O)O)CCN(CC(=O)O)CCN(CC(=O)O)CC1,10.1016/0020-1693(96)05182-1,dioury2014,24.67
2,rev_142,142,O=C(O)CN(CCN(CCN(CC(=O)O)CC(=O)O)CC(=O)O)CCN(C...,10.1016/0223-5234(88)90094-3,dioury2014,28.40
3,rev_035,35,CC(CO)N1CCN(CC(=O)O)CCN(CC(=O)O)CCN(CC(=O)O)CC1,10.1021/ic00095a028,dioury2014,23.90
4,rev_170,A39,O=C(O)CN(CC(=O)O)Cc1cccc(CN(CC(=O)O)CC(=O)O)n1,10.1039/b817343e,uzal2022,18.60
...,...,...,...,...,...,...
212,rev_136,136,CN(CC(O)C(O)C(O)C(O)CO)C(=O)C(COCc1ccccc1)N1CC...,10.1021/ic00038a023,dioury2014,26.40
213,rev_074,74,CCN(CCN(CC(=O)O)CC(=O)O)CCN(CC(=O)O)CC(=O)O,10.1021/ic00212a005,dioury2014,17.79
214,rev_227,T12,CCCCNC(=O)CN(CCN(CCN(CC(=O)O)CC(=O)O)CC(=O)O)C...,10.1039/C7DT04104G,uzal2022,18.78
215,rev_062,62,Nc1ccc(CC(C(=O)O)N(CCN(CC(=O)O)CC(=O)O)CCN(CC(...,10.1021/jm9602118,dioury2014,21.99
216,rev_184,A66,O=C(O)CN(CC(=O)O)C(=O)c1ccccc1,10.1016/S0010-8545(99)00237-4,uzal2022,7.04

In [13]:
# save data
df_unique_random.to_csv('../data/Gd/final/merged_reviews_clean.csv', index = None)